backend:
  name: github
  repo: rchrdnsh/arrow-gtp
publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads

collections:

  - name: "tours"
    label: "Tours"
    folder: "src/tours"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Embed", name: "embed", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "work"
    label: "Work"
    folder: "src/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      
  - name: "team"
    identifier_field: name
    label: "Team"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Picture", name: "picture", widget: "image" }
      - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
